# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activejob-traceable` gem.
# Please instead update this file by running `bin/tapioca gem activejob-traceable`.


# source://activejob-traceable//lib/activejob/traceable.rb#12
module ActiveJob
  class << self
    # source://activejob/7.1.5.1/lib/active_job/queue_adapter.rb#7
    def adapter_name(adapter); end

    # source://activejob/7.1.5.1/lib/active_job/deprecator.rb#4
    def deprecator; end

    # source://activejob/7.1.5.1/lib/active_job/gem_version.rb#5
    def gem_version; end

    # source://activejob/7.1.5.1/lib/active_job/enqueuing.rb#14
    def perform_all_later(*jobs); end

    # source://activejob/7.1.5.1/lib/active_job.rb#56
    def use_big_decimal_serializer; end

    # source://activejob/7.1.5.1/lib/active_job.rb#56
    def use_big_decimal_serializer=(_arg0); end

    # source://activejob/7.1.5.1/lib/active_job.rb#64
    def verbose_enqueue_logs; end

    # source://activejob/7.1.5.1/lib/active_job.rb#64
    def verbose_enqueue_logs=(_arg0); end

    # source://activejob/7.1.5.1/lib/active_job/version.rb#7
    def version; end

    private

    # source://activejob/7.1.5.1/lib/active_job/instrumentation.rb#6
    def instrument_enqueue_all(queue_adapter, jobs); end
  end
end

class ActiveJob::Base
  # source://activejob-traceable//lib/activejob/traceable/traceable.rb#10
  def initialize(*args, **_arg1); end

  # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#70
  def __callbacks; end

  # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#70
  def __callbacks?; end

  # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#963
  def _enqueue_callbacks; end

  # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#963
  def _perform_callbacks; end

  # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#951
  def _run_enqueue_callbacks(&block); end

  # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#951
  def _run_perform_callbacks(&block); end

  # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#12
  def after_discard_procs; end

  # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#12
  def after_discard_procs=(_arg0); end

  # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#12
  def after_discard_procs?; end

  # source://activejob-traceable//lib/activejob/traceable/traceable.rb#22
  def deserialize(job_data); end

  # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#48
  def lock_options; end

  # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#48
  def lock_options?; end

  # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#47
  def lock_strategy_class; end

  # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#47
  def lock_strategy_class?; end

  # source://activejob/7.1.5.1/lib/active_job/logging.rb#11
  def logger; end

  # source://activejob/7.1.5.1/lib/active_job/logging.rb#11
  def logger=(val); end

  # source://activejob/7.1.5.1/lib/active_job/queue_adapter.rb#26
  def queue_adapter(&block); end

  # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#57
  def queue_name_prefix; end

  # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#57
  def queue_name_prefix=(_arg0); end

  # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#57
  def queue_name_prefix?; end

  # source://activesupport/7.1.5.1/lib/active_support/rescuable.rb#15
  def rescue_handlers; end

  # source://activesupport/7.1.5.1/lib/active_support/rescuable.rb#15
  def rescue_handlers=(_arg0); end

  # source://activesupport/7.1.5.1/lib/active_support/rescuable.rb#15
  def rescue_handlers?; end

  # source://activejob-traceable//lib/activejob/traceable/traceable.rb#17
  def serialize; end

  # source://sidekiq/7.3.7/lib/sidekiq/job.rb#141
  def sidekiq_options_hash; end

  # source://sidekiq/7.3.7/lib/sidekiq/job.rb#153
  def sidekiq_options_hash=(_arg0); end

  # source://sidekiq/7.3.7/lib/sidekiq/job.rb#141
  def sidekiq_retries_exhausted_block; end

  # source://sidekiq/7.3.7/lib/sidekiq/job.rb#153
  def sidekiq_retries_exhausted_block=(_arg0); end

  # source://sidekiq/7.3.7/lib/sidekiq/job.rb#141
  def sidekiq_retry_in_block; end

  # source://sidekiq/7.3.7/lib/sidekiq/job.rb#153
  def sidekiq_retry_in_block=(_arg0); end

  # source://activejob-traceable//lib/activejob/traceable/traceable.rb#8
  def tracing_info; end

  # source://activejob-traceable//lib/activejob/traceable/traceable.rb#8
  def tracing_info=(_arg0); end

  private

  # source://activejob-traceable//lib/activejob/traceable/logging_patch.rb#11
  def tag_logger(*tags); end

  class << self
    # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#70
    def __callbacks; end

    # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#70
    def __callbacks=(value); end

    # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#70
    def __callbacks?; end

    # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#955
    def _enqueue_callbacks; end

    # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#959
    def _enqueue_callbacks=(value); end

    # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#955
    def _perform_callbacks; end

    # source://activesupport/7.1.5.1/lib/active_support/callbacks.rb#959
    def _perform_callbacks=(value); end

    # source://activejob/7.1.5.1/lib/active_job/queue_adapter.rb#24
    def _queue_adapter; end

    # source://activejob/7.1.5.1/lib/active_job/queue_adapter.rb#24
    def _queue_adapter=(value); end

    # source://activejob/7.1.5.1/lib/active_job/queue_adapter.rb#23
    def _queue_adapter_name; end

    # source://activejob/7.1.5.1/lib/active_job/queue_adapter.rb#23
    def _queue_adapter_name=(value); end

    # source://activejob/7.1.5.1/lib/active_job/test_helper.rb#19
    def _test_adapter; end

    # source://activejob/7.1.5.1/lib/active_job/test_helper.rb#19
    def _test_adapter=(value); end

    # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#12
    def after_discard_procs; end

    # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#12
    def after_discard_procs=(value); end

    # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#12
    def after_discard_procs?; end

    # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#48
    def lock_options; end

    # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#48
    def lock_options=(value); end

    # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#48
    def lock_options?; end

    # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#47
    def lock_strategy_class; end

    # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#47
    def lock_strategy_class=(value); end

    # source://activejob-uniqueness/0.3.2/lib/active_job/uniqueness/active_job_patch.rb#47
    def lock_strategy_class?; end

    # source://activejob/7.1.5.1/lib/active_job/logging.rb#12
    def log_arguments; end

    # source://activejob/7.1.5.1/lib/active_job/logging.rb#12
    def log_arguments=(value); end

    # source://activejob/7.1.5.1/lib/active_job/logging.rb#12
    def log_arguments?; end

    # source://activejob/7.1.5.1/lib/active_job/logging.rb#11
    def logger; end

    # source://activejob/7.1.5.1/lib/active_job/logging.rb#11
    def logger=(val); end

    # source://activejob/7.1.5.1/lib/active_job/queue_priority.rb#49
    def priority; end

    # source://activejob/7.1.5.1/lib/active_job/queue_priority.rb#49
    def priority=(value); end

    # source://activejob/7.1.5.1/lib/active_job/queue_priority.rb#49
    def priority?; end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#55
    def queue_name; end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#55
    def queue_name=(value); end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#55
    def queue_name?; end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#56
    def queue_name_delimiter; end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#56
    def queue_name_delimiter=(value); end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#56
    def queue_name_delimiter?; end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#57
    def queue_name_prefix; end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#57
    def queue_name_prefix=(value); end

    # source://activejob/7.1.5.1/lib/active_job/queue_name.rb#57
    def queue_name_prefix?; end

    # source://activesupport/7.1.5.1/lib/active_support/rescuable.rb#15
    def rescue_handlers; end

    # source://activesupport/7.1.5.1/lib/active_support/rescuable.rb#15
    def rescue_handlers=(value); end

    # source://activesupport/7.1.5.1/lib/active_support/rescuable.rb#15
    def rescue_handlers?; end

    # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#11
    def retry_jitter; end

    # source://activejob/7.1.5.1/lib/active_job/exceptions.rb#11
    def retry_jitter=(value); end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#108
    def sidekiq_options_hash; end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#116
    def sidekiq_options_hash=(val); end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#108
    def sidekiq_retries_exhausted_block; end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#116
    def sidekiq_retries_exhausted_block=(val); end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#108
    def sidekiq_retry_in_block; end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#116
    def sidekiq_retry_in_block=(val); end

    private

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#103
    def __synchronized_sidekiq_options_hash; end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#103
    def __synchronized_sidekiq_retries_exhausted_block; end

    # source://sidekiq/7.3.7/lib/sidekiq/job.rb#103
    def __synchronized_sidekiq_retry_in_block; end
  end
end

# source://activejob-traceable//lib/activejob/traceable.rb#13
module ActiveJob::Traceable
  extend ::ActiveSupport::Concern

  private

  # source://activejob-traceable//lib/activejob/traceable/traceable.rb#37
  def add_telemetry_data!; end

  # source://activejob-traceable//lib/activejob/traceable.rb#16
  def tracing_info_getter=(lambda); end

  # source://activejob-traceable//lib/activejob/traceable.rb#28
  def tracing_info_setter=(lambda); end

  class << self
    # source://activejob-traceable//lib/activejob/traceable/traceable.rb#46
    def tracing_info_getter; end

    # source://activejob-traceable//lib/activejob/traceable.rb#16
    def tracing_info_getter=(lambda); end

    # source://activejob-traceable//lib/activejob/traceable/traceable.rb#50
    def tracing_info_setter; end

    # source://activejob-traceable//lib/activejob/traceable.rb#28
    def tracing_info_setter=(lambda); end
  end
end

# source://activejob-traceable//lib/activejob/traceable/logging_patch.rb#5
module ActiveJob::Traceable::LoggingPatch
  extend ::ActiveSupport::Concern
end
