# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CreditNoteMailer`.
# Please instead update this file by running `bin/tapioca dsl CreditNoteMailer`.


class CreditNoteMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def created; end

    sig { returns(::ActionMailer::MessageDelivery) }
    def set_shared_variables; end
  end
end
