# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DataExportMailer`.
# Please instead update this file by running `bin/tapioca dsl DataExportMailer`.


class DataExportMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def completed; end

    sig { returns(::ActionMailer::MessageDelivery) }
    def set_shared_variables; end
  end
end
