# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Coupons::LimitationInput`.
# Please instead update this file by running `bin/tapioca dsl Types::Coupons::LimitationInput`.


class Types::Coupons::LimitationInput
  sig { returns(T.nilable(T::Array[::String])) }
  def billable_metric_ids; end

  sig { returns(T.nilable(T::Array[::String])) }
  def plan_ids; end
end
