# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Charges::VolumeRangeInput`.
# Please instead update this file by running `bin/tapioca dsl Types::Charges::VolumeRangeInput`.


class Types::Charges::VolumeRangeInput
  sig { returns(::String) }
  def flat_amount; end

  sig { returns(::Integer) }
  def from_value; end

  sig { returns(::String) }
  def per_unit_amount; end

  sig { returns(T.nilable(::Integer)) }
  def to_value; end
end
