# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::DataExports::Invoices::CreateInput`.
# Please instead update this file by running `bin/tapioca dsl Types::DataExports::Invoices::CreateInput`.


class Types::DataExports::Invoices::CreateInput
  sig { returns(::Types::DataExports::Invoices::FiltersInput) }
  def filters; end

  sig { returns(::String) }
  def format; end

  sig { returns(::String) }
  def resource_type; end
end
